#!/usr/bin/env python3
"""
Enrich restaurant data with neighborhood and cuisine type information.
Comprehensive database of NYC restaurants.
"""

import json

# Comprehensive restaurant data - all restaurants from the list
KNOWN_RESTAURANTS = {
    # === A ===
    "4 Charles": {"neighborhood": "West Village", "cuisine_type": "American"},
    "4F": {"neighborhood": "East Village", "cuisine_type": "Japanese"},
    "8282": {"neighborhood": "Koreatown", "cuisine_type": "Korean"},
    "Acme": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Adda": {"neighborhood": "Long Island City", "cuisine_type": "Indian"},
    "Alba Acconto": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Aldama": {"neighborhood": "Bushwick", "cuisine_type": "Mexican"},
    "Alessa's": {"neighborhood": "Penn District", "cuisine_type": "Italian"},
    "Alice": {"neighborhood": "Flatiron", "cuisine_type": "American"},
    "All Antico Vinaio": {"neighborhood": "Multiple", "cuisine_type": "Italian"},
    "Also Sohm wine bar": {"neighborhood": "Theatre District", "cuisine_type": "Wine Bar"},
    "Amarena": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Anfora": {"neighborhood": "West Village", "cuisine_type": "Wine Bar"},
    "Angelina Paris": {"neighborhood": "SoHo", "cuisine_type": "French"},
    "Angels Share": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Andie's Eats": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Apollo Bagels": {"neighborhood": "SoHo", "cuisine_type": "Bakery"},
    "Apotheke": {"neighborhood": "Chinatown", "cuisine_type": "Bar/Cocktails"},
    "Apt 5": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "Ariari": {"neighborhood": "NoHo", "cuisine_type": "Korean"},
    "Atla": {"neighborhood": "NoHo", "cuisine_type": "Mexican"},
    "Atoboy": {"neighborhood": "NoMad", "cuisine_type": "Korean"},
    "Au Cheval": {"neighborhood": "Tribeca", "cuisine_type": "American"},
    
    # === B ===
    "B&H Dairy": {"neighborhood": "East Village", "cuisine_type": "American"},
    "B'artusi": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Babs": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "Baby Blues": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Baby Luc's": {"neighborhood": "Cobble Hill", "cuisine_type": "Italian"},
    "Bad Roman": {"neighborhood": "Columbus Circle", "cuisine_type": "Italian"},
    "Bambina Blue": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Bandits": {"neighborhood": "Chinatown", "cuisine_type": "Mexican"},
    "Bangkok Supper Club": {"neighborhood": "Lower East Side", "cuisine_type": "Thai"},
    "Banter": {"neighborhood": "East Village", "cuisine_type": "American"},
    "Bar Bianche": {"neighborhood": "East Village", "cuisine_type": "Italian"},
    "Bar Bonobo": {"neighborhood": "Chelsea", "cuisine_type": "Bar/Cocktails"},
    "Bar Bête": {"neighborhood": "West Village", "cuisine_type": "French"},
    "Bar Contra": {"neighborhood": "SoHo", "cuisine_type": "Mexican"},
    "Bar Miller": {"neighborhood": "SoHo", "cuisine_type": "Japanese"},
    "Bar Pasquale": {"neighborhood": "Nolita", "cuisine_type": "Italian"},
    "Bar Primi": {"neighborhood": "NoHo", "cuisine_type": "Italian"},
    "Bar Revival": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "Bar Snack": {"neighborhood": "NoHo", "cuisine_type": "Bar/Cocktails"},
    "Bar Tulix": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Bar Whimsy": {"neighborhood": "Multiple", "cuisine_type": "Bar/Cocktails"},
    "Bar à Part": {"neighborhood": "West Village", "cuisine_type": "Wine Bar"},
    "Bar vivant": {"neighborhood": "Upper East Side", "cuisine_type": "Wine Bar"},
    "Batsu": {"neighborhood": "Lower East Side", "cuisine_type": "Japanese"},
    "Beefbar": {"neighborhood": "SoHo", "cuisine_type": "Steakhouse"},
    "Bergamo's": {"neighborhood": "FiDi", "cuisine_type": "Bar/Cocktails"},
    "Berimbau": {"neighborhood": "West Village", "cuisine_type": "Brazilian"},
    "Bernies": {"neighborhood": "Greenpoint", "cuisine_type": "American"},
    "Biga Bite": {"neighborhood": "Lower East Side", "cuisine_type": "Pizza"},
    "Bleecker Street Pizza": {"neighborhood": "West Village", "cuisine_type": "Pizza"},
    "Borgo": {"neighborhood": "Flatiron", "cuisine_type": "Italian"},
    "Boucherie": {"neighborhood": "West Village", "cuisine_type": "French"},
    "Breakfast by Salt's Cure": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Bridges": {"neighborhood": "Chinatown", "cuisine_type": "American"},
    "Bronson's Burgers": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Brooklyn Crab": {"neighborhood": "Red Hook", "cuisine_type": "Seafood"},
    "Brooklyn Delicatessen": {"neighborhood": "Brooklyn", "cuisine_type": "Deli"},
    "Buba Bureka": {"neighborhood": "Greenwich Village", "cuisine_type": "Middle Eastern"},
    "Bubby's": {"neighborhood": "Tribeca", "cuisine_type": "American"},
    "Butler Coffee": {"neighborhood": "Williamsburg", "cuisine_type": "Coffee/Cafe"},
    
    # === C ===
    "C as in Charlie": {"neighborhood": "Upper East Side", "cuisine_type": "American"},
    "Café Chelsea": {"neighborhood": "Chelsea", "cuisine_type": "Coffee/Cafe"},
    "Cafe Cluny": {"neighborhood": "West Village", "cuisine_type": "French"},
    "Cafe Balerica": {"neighborhood": "Lower East Side", "cuisine_type": "Mediterranean"},
    "Café Commerce": {"neighborhood": "Upper East Side", "cuisine_type": "French"},
    "Café Paradiso": {"neighborhood": "SoHo", "cuisine_type": "Coffee/Cafe"},
    "Café Zaffri": {"neighborhood": "Union Square", "cuisine_type": "Persian"},
    "Caffe Coretto": {"neighborhood": "West Village", "cuisine_type": "Coffee/Cafe"},
    "Canary Club": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "Carinito": {"neighborhood": "Union Square", "cuisine_type": "Mexican"},
    "Carlota": {"neighborhood": "West Village", "cuisine_type": "Spanish"},
    "Carlotto": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Casa Carmen": {"neighborhood": "West Village", "cuisine_type": "Spanish"},
    "Casa Cruz": {"neighborhood": "Upper East Side", "cuisine_type": "Latin"},
    "Casino": {"neighborhood": "SoHo", "cuisine_type": "Italian"},
    "Cecconi's": {"neighborhood": "Dumbo", "cuisine_type": "Italian"},
    "Cecchi's": {"neighborhood": "Williamsburg", "cuisine_type": "Italian"},
    "Cello's Pizzeria": {"neighborhood": "East Village", "cuisine_type": "Pizza"},
    "Ceres": {"neighborhood": "SoHo", "cuisine_type": "Pizza"},
    "Cervo's": {"neighborhood": "Lower East Side", "cuisine_type": "Seafood"},
    "Chama Mama": {"neighborhood": "Flatiron", "cuisine_type": "Georgian"},
    "Champagne Problems": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Champers Social Club": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Charcuterie": {"neighborhood": "Midtown", "cuisine_type": "American"},
    "Chef Competition at Hudson Table": {"neighborhood": "Hudson Yards", "cuisine_type": "American"},
    "Chelsea living room": {"neighborhood": "Chelsea", "cuisine_type": "Bar/Cocktails"},
    "Chino Grande": {"neighborhood": "NoHo", "cuisine_type": "Asian"},
    "Chloe": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "Ci Siamo": {"neighborhood": "Hudson Yards", "cuisine_type": "Italian"},
    "Ciao Evento pasta party": {"neighborhood": "Multiple", "cuisine_type": "Italian"},
    "Ciao Gloria": {"neighborhood": "Prospect Heights", "cuisine_type": "Italian"},
    "Clemente Bar": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "Coarse NY": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Cobble & Co": {"neighborhood": "Cobble Hill", "cuisine_type": "American"},
    "Coco Pazzeria": {"neighborhood": "SoHo", "cuisine_type": "Italian"},
    "COCODAQ": {"neighborhood": "Flatiron", "cuisine_type": "Asian"},
    "Cocoran": {"neighborhood": "Lower East Side", "cuisine_type": "Japanese"},
    "Comal": {"neighborhood": "Chinatown", "cuisine_type": "Mexican"},
    "Contra": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "Conwell Coffee Hall": {"neighborhood": "FiDi", "cuisine_type": "Coffee/Cafe"},
    "Corima": {"neighborhood": "Lower East Side", "cuisine_type": "Mexican"},
    "Corner Bar": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Corner Bistro": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Crazy Pizza": {"neighborhood": "SoHo", "cuisine_type": "Pizza"},
    "Crevette": {"neighborhood": "West Village", "cuisine_type": "Seafood"},
    "Crispy Heaven": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Cucina Alba": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Cuerno": {"neighborhood": "Theatre District", "cuisine_type": "Mexican"},
    "Culture Espresso": {"neighborhood": "Midtown", "cuisine_type": "Coffee/Cafe"},
    
    # === D ===
    "Da Andrea": {"neighborhood": "Chelsea", "cuisine_type": "Italian"},
    "Da Toscano": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Dame": {"neighborhood": "West Village", "cuisine_type": "Seafood"},
    "Dante": {"neighborhood": "Greenwich Village", "cuisine_type": "Bar/Cocktails"},
    "Dante Apertivio Bar": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Davelle": {"neighborhood": "Lower East Side", "cuisine_type": "Japanese"},
    "Day Drinks": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Dear Stranger": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Death by Pizza": {"neighborhood": "Nolita", "cuisine_type": "Pizza"},
    "Desert 5 Spot": {"neighborhood": "Williamsburg", "cuisine_type": "Bar/Cocktails"},
    "Dialogue Café": {"neighborhood": "Lower East Side", "cuisine_type": "Coffee/Cafe"},
    "Dirty Taco Tacomakase": {"neighborhood": "Midtown", "cuisine_type": "Mexican"},
    "DND": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Donut Pub": {"neighborhood": "West Village", "cuisine_type": "Bakery"},
    "Dough": {"neighborhood": "Flatiron", "cuisine_type": "Bakery"},
    "Drai's Supper Club": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Drift In": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Dudley's": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    
    # === E ===
    "Early Terrible": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "Earthage Must Be Destroyed": {"neighborhood": "Brooklyn", "cuisine_type": "American"},
    "East Village Pizza": {"neighborhood": "East Village", "cuisine_type": "Pizza"},
    "Eel Bar": {"neighborhood": "Williamsburg", "cuisine_type": "Seafood"},
    "El Camino": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "El Nico": {"neighborhood": "West Village", "cuisine_type": "Mexican"},
    "Ella Funt": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Elvis": {"neighborhood": "NoHo", "cuisine_type": "Wine Bar"},
    "Emilia by Nai x Coffee Project": {"neighborhood": "SoHo", "cuisine_type": "Coffee/Cafe"},
    "Emmetts on Grove": {"neighborhood": "West Village", "cuisine_type": "Pizza"},
    "Employees Only": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Emporio": {"neighborhood": "Nolita", "cuisine_type": "Italian"},
    "Ensenada": {"neighborhood": "Lower East Side", "cuisine_type": "Mexican"},
    "Experimental Cocktail Club": {"neighborhood": "Flatiron", "cuisine_type": "Bar/Cocktails"},
    "Extra Virgin": {"neighborhood": "West Village", "cuisine_type": "Mediterranean"},
    
    # === F ===
    "F&F Restaurant": {"neighborhood": "Carroll Gardens", "cuisine_type": "Italian"},
    "Falanzi": {"neighborhood": "West Village", "cuisine_type": "Asian"},
    "Fan Fan Donuts": {"neighborhood": "Greenpoint", "cuisine_type": "Bakery"},
    "Felix Roasting Co.": {"neighborhood": "SoHo", "cuisine_type": "Coffee/Cafe"},
    "Fiaschetteria Pistoia": {"neighborhood": "NoHo", "cuisine_type": "Italian"},
    "Fini Pizza at Dante Fridays 12-6": {"neighborhood": "West Village", "cuisine_type": "Pizza"},
    "Five Leaves": {"neighborhood": "Greenpoint", "cuisine_type": "American"},
    "Foreigner": {"neighborhood": "Chelsea", "cuisine_type": "Coffee/Cafe"},
    "Forsythia": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "Fortuna": {"neighborhood": "Gramercy", "cuisine_type": "Middle Eastern"},
    "Fossetta": {"neighborhood": "Brooklyn", "cuisine_type": "Italian"},
    "Foul Witch": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Fouquets": {"neighborhood": "Tribeca", "cuisine_type": "French"},
    "Frances at Casa Cruz": {"neighborhood": "Upper East Side", "cuisine_type": "American"},
    "Frena": {"neighborhood": "Hell's Kitchen", "cuisine_type": "Mediterranean"},
    "Frenchette": {"neighborhood": "Tribeca", "cuisine_type": "French"},
    "Friend of a Farmer": {"neighborhood": "Gramercy", "cuisine_type": "American"},
    "Frog Club": {"neighborhood": "Midtown", "cuisine_type": "French"},
    
    # === G ===
    "Gab's": {"neighborhood": "East Village", "cuisine_type": "American"},
    "Gallow Green": {"neighborhood": "Chelsea", "cuisine_type": "Bar/Cocktails"},
    "Garrett East": {"neighborhood": "East Village", "cuisine_type": "American"},
    "Gazette": {"neighborhood": "Upper East Side", "cuisine_type": "Wine Bar"},
    "Gelatoville": {"neighborhood": "Chelsea", "cuisine_type": "Dessert"},
    "Gemma at the Bowery Hotel": {"neighborhood": "East Village", "cuisine_type": "Italian"},
    "Gilligan's": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "Gjelina": {"neighborhood": "NoMad", "cuisine_type": "American"},
    "Gnocco": {"neighborhood": "East Village", "cuisine_type": "Italian"},
    "Go Go Sing": {"neighborhood": "Flatiron", "cuisine_type": "Bar/Cocktails"},
    "Golden Diner": {"neighborhood": "Chinatown", "cuisine_type": "American"},
    "Golden Hof + NY Kimchi": {"neighborhood": "Midtown", "cuisine_type": "Korean"},
    "Good Guys": {"neighborhood": "NoHo", "cuisine_type": "Bar/Cocktails"},
    "Good Thanks": {"neighborhood": "Nolita", "cuisine_type": "Coffee/Cafe"},
    "Green lane coffee": {"neighborhood": "Upper East Side", "cuisine_type": "Coffee/Cafe"},
    "Greenwich Street Tavern": {"neighborhood": "Tribeca", "cuisine_type": "American"},
    "Greywind": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "The Gyro Project": {"neighborhood": "Upper West Side", "cuisine_type": "Greek"},
    
    # === H ===
    "Hags": {"neighborhood": "East Village", "cuisine_type": "American"},
    "Hamburger America": {"neighborhood": "East Village", "cuisine_type": "American"},
    "The Hand Roll Bar": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Happier Grocery": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Harris Bakes": {"neighborhood": "Brooklyn", "cuisine_type": "Bakery"},
    "Harry's Table": {"neighborhood": "Hudson Yards", "cuisine_type": "American"},
    "Hawksmoor": {"neighborhood": "Tribeca", "cuisine_type": "Steakhouse"},
    "Her Name Was Carmen": {"neighborhood": "Lower East Side", "cuisine_type": "Spanish"},
    "Hero's": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "Hidden Grounds": {"neighborhood": "East Village", "cuisine_type": "Coffee/Cafe"},
    "Hilot": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "Ho Foods": {"neighborhood": "East Village", "cuisine_type": "Taiwanese"},
    "Hoexter's": {"neighborhood": "Midtown", "cuisine_type": "Deli"},
    "Holy Water": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Homemade by Bruno pasta making class": {"neighborhood": "Multiple", "cuisine_type": "Italian"},
    "Honestea": {"neighborhood": "NoHo", "cuisine_type": "Coffee/Cafe"},
    "Hudson Clearwater": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Hungry Llama cafe": {"neighborhood": "Multiple", "cuisine_type": "Coffee/Cafe"},
    "Hussey pop-up at Standard EV": {"neighborhood": "East Village", "cuisine_type": "Mexican"},
    
    # === I ===
    "I Sodi": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Il cantinori": {"neighborhood": "Greenwich Village", "cuisine_type": "Italian"},
    "Il Fiorista": {"neighborhood": "Flatiron", "cuisine_type": "Italian"},
    "Industry Kitchen": {"neighborhood": "South Street Seaport", "cuisine_type": "American"},
    "Isla and Co": {"neighborhood": "Midtown", "cuisine_type": "Bar/Cocktails"},
    "Ixta": {"neighborhood": "Lower East Side", "cuisine_type": "Mexican"},
    
    # === J ===
    "Jac's on Bond": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Jack and Charlie's 118": {"neighborhood": "Upper East Side", "cuisine_type": "American"},
    "Jack's Wife Freda": {"neighborhood": "SoHo", "cuisine_type": "Mediterranean"},
    "Jackdaw": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Jaffa Cocktail and Raw Bar": {"neighborhood": "Lower East Side", "cuisine_type": "Middle Eastern"},
    "Janie's Life Changing Baked Goods": {"neighborhood": "West Village", "cuisine_type": "Bakery"},
    "Jazba": {"neighborhood": "West Village", "cuisine_type": "Indian"},
    "Jean's Lafayette": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Joe's Pizza": {"neighborhood": "West Village", "cuisine_type": "Pizza"},
    "Jolene": {"neighborhood": "Murray Hill", "cuisine_type": "American"},
    "Joseph Leonard": {"neighborhood": "West Village", "cuisine_type": "American"},
    "JR & Son": {"neighborhood": "Greenpoint", "cuisine_type": "Bakery"},
    "Jue Lan Club": {"neighborhood": "Flatiron", "cuisine_type": "Chinese"},
    
    # === K ===
    "Kame": {"neighborhood": "SoHo", "cuisine_type": "Japanese"},
    "Kanyakumari": {"neighborhood": "Union Square", "cuisine_type": "Indian"},
    "Kerber's Farm": {"neighborhood": "Long Island", "cuisine_type": "American"},
    "Keste": {"neighborhood": "West Village", "cuisine_type": "Pizza"},
    "Kimika": {"neighborhood": "Nolita", "cuisine_type": "Japanese"},
    "Kobano": {"neighborhood": "Bowery", "cuisine_type": "Japanese"},
    "Kobrick's": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Koloman": {"neighborhood": "Flatiron", "cuisine_type": "Austrian"},
    "Kubeh": {"neighborhood": "Greenwich Village", "cuisine_type": "Middle Eastern"},
    "KYU": {"neighborhood": "Flatiron", "cuisine_type": "Asian"},
    "Kyma Flatiron": {"neighborhood": "Flatiron", "cuisine_type": "Greek"},
    
    # === L ===
    "L&B Spumoni Gardens": {"neighborhood": "Brooklyn", "cuisine_type": "Pizza"},
    "L'Antica Pizzeria da Michele": {"neighborhood": "Greenwich Village", "cuisine_type": "Pizza"},
    "L'artusi": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "L'incontra by Rocco": {"neighborhood": "Upper East Side", "cuisine_type": "Italian"},
    "La Bomboniera": {"neighborhood": "Upper East Side", "cuisine_type": "Italian"},
    "La Cabra": {"neighborhood": "Lower East Side", "cuisine_type": "Coffee/Cafe"},
    "La Esquina": {"neighborhood": "Nolita", "cuisine_type": "Mexican"},
    "Lamalo": {"neighborhood": "Gramercy", "cuisine_type": "Middle Eastern"},
    "Lamia's Fish Market": {"neighborhood": "East Village", "cuisine_type": "Seafood"},
    "Le B": {"neighborhood": "SoHo", "cuisine_type": "French"},
    "Le Bar Penelope": {"neighborhood": "Upper East Side", "cuisine_type": "Bar/Cocktails"},
    "Le Baratin": {"neighborhood": "Brooklyn", "cuisine_type": "French"},
    "Le Chêne": {"neighborhood": "West Village", "cuisine_type": "French"},
    "Le Crocodile": {"neighborhood": "Williamsburg", "cuisine_type": "French"},
    "Le Gamin": {"neighborhood": "Brooklyn", "cuisine_type": "French"},
    "Leonessa": {"neighborhood": "FiDi", "cuisine_type": "Bar/Cocktails"},
    "Libertine": {"neighborhood": "West Village", "cuisine_type": "French"},
    "Lilia": {"neighborhood": "Williamsburg", "cuisine_type": "Italian"},
    "Lillistar": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Little Charli": {"neighborhood": "SoHo", "cuisine_type": "Italian"},
    "Little Mint": {"neighborhood": "Multiple", "cuisine_type": "Thai"},
    "Little Owl": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Little Shop": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "Locanda Verde": {"neighborhood": "Tribeca", "cuisine_type": "Italian"},
    "Lodi": {"neighborhood": "Rockefeller Center", "cuisine_type": "Italian"},
    "Lola Taverna": {"neighborhood": "West Village", "cuisine_type": "Greek"},
    "Los Tacos No. 1": {"neighborhood": "Chelsea", "cuisine_type": "Mexican"},
    "Lucy's": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Lucky Rabbit Noodle": {"neighborhood": "Lower East Side", "cuisine_type": "Chinese"},
    "Lupetto": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    
    # === M ===
    "Ma Dé": {"neighborhood": "West Village", "cuisine_type": "Vietnamese"},
    "Madeline's Martini": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Madison fare": {"neighborhood": "Upper East Side", "cuisine_type": "Greek"},
    "Mah-de-Zehr": {"neighborhood": "West Village", "cuisine_type": "Bakery"},
    "Maison Passerelle": {"neighborhood": "FiDi", "cuisine_type": "French"},
    "Maison Premiere": {"neighborhood": "Williamsburg", "cuisine_type": "Bar/Cocktails"},
    "Maki Kosaka": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Maki mono": {"neighborhood": "Chelsea", "cuisine_type": "Japanese"},
    "Malibu Farm": {"neighborhood": "Dumbo", "cuisine_type": "American"},
    "Mamma Mezze": {"neighborhood": "Flatiron", "cuisine_type": "Mediterranean"},
    "Manero's Pizza": {"neighborhood": "East Village", "cuisine_type": "Pizza"},
    "Mangetsu": {"neighborhood": "Chelsea", "cuisine_type": "Japanese"},
    "Mari.ne": {"neighborhood": "SoHo", "cuisine_type": "Seafood"},
    "Marlow": {"neighborhood": "Upper East Side", "cuisine_type": "Mediterranean"},
    "Martiny's": {"neighborhood": "NoMad", "cuisine_type": "Bar/Cocktails"},
    "Mary O's Irish Soda Bread Shop": {"neighborhood": "East Village", "cuisine_type": "Bakery"},
    "Massara": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Meduza": {"neighborhood": "Greenpoint", "cuisine_type": "Mediterranean"},
    "Mel": {"neighborhood": "Tribeca", "cuisine_type": "American"},
    "Mel's": {"neighborhood": "West Village", "cuisine_type": "American"},
    "MENO": {"neighborhood": "Williamsburg", "cuisine_type": "Italian"},
    "Mesiba": {"neighborhood": "Lower East Side", "cuisine_type": "Middle Eastern"},
    "Messy": {"neighborhood": "SoHo", "cuisine_type": "Middle Eastern"},
    "Midnight Blue": {"neighborhood": "Gramercy", "cuisine_type": "Bar/Cocktails"},
    "Milady's": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Milk flower": {"neighborhood": "Astoria", "cuisine_type": "Pizza"},
    "Milu": {"neighborhood": "FiDi", "cuisine_type": "American"},
    "Minetta Tavern": {"neighborhood": "Greenwich Village", "cuisine_type": "American"},
    "Miracle on 9th Street": {"neighborhood": "East Village", "cuisine_type": "Italian"},
    "Miriam": {"neighborhood": "Upper West Side", "cuisine_type": "Middle Eastern"},
    "Misi": {"neighborhood": "Williamsburg", "cuisine_type": "Italian"},
    "Mister Dips": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Mitsuru": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Momofuku Ko": {"neighborhood": "East Village", "cuisine_type": "Japanese"},
    "Momofuku Noodle Bar": {"neighborhood": "East Village", "cuisine_type": "Japanese"},
    "Momofuku Ssam Bar": {"neighborhood": "East Village", "cuisine_type": "Japanese"},
    "Monkey Bar": {"neighborhood": "Midtown", "cuisine_type": "American"},
    "Monsieur": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Monsieur Bistro": {"neighborhood": "Upper East Side", "cuisine_type": "French"},
    "Monsieur Vo": {"neighborhood": "East Village", "cuisine_type": "Vietnamese"},
    "Moody Tongue Pizza": {"neighborhood": "West Village", "cuisine_type": "Pizza"},
    "Moody Tounge Sushi": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Moonflower": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Morganstern's Burgers, Fries, and Pies": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "Moustache": {"neighborhood": "East Village", "cuisine_type": "Middle Eastern"},
    "Mr. Purple": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "Museum Coffee": {"neighborhood": "Midtown", "cuisine_type": "Coffee/Cafe"},
    "Mymo Kafé": {"neighborhood": "Times Square", "cuisine_type": "Coffee/Cafe"},
    
    # === N ===
    "Nat's on Bank": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Nightly's": {"neighborhood": "Upper East Side", "cuisine_type": "American"},
    "Noa, a café": {"neighborhood": "SoHo", "cuisine_type": "Coffee/Cafe"},
    "Not as bitter": {"neighborhood": "West Village", "cuisine_type": "Coffee/Cafe"},
    "Nur": {"neighborhood": "Flatiron", "cuisine_type": "Middle Eastern"},
    
    # === O ===
    "Oases": {"neighborhood": "Chelsea", "cuisine_type": "American"},
    "Obvio": {"neighborhood": "NoMad", "cuisine_type": "Bar/Cocktails"},
    "Olio e Piu": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Omakaseed": {"neighborhood": "Brooklyn", "cuisine_type": "Japanese"},
    "One White Street": {"neighborhood": "Tribeca", "cuisine_type": "American"},
    "Only Love Strangers": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Opto": {"neighborhood": "Flatiron", "cuisine_type": "Italian"},
    "Overstory": {"neighborhood": "FiDi", "cuisine_type": "Bar/Cocktails"},
    "Oxomoco": {"neighborhood": "Greenpoint", "cuisine_type": "Mexican"},
    "Oyamel by José": {"neighborhood": "Hudson Yards", "cuisine_type": "Mexican"},
    
    # === P ===
    "Palma": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Pantry": {"neighborhood": "SoHo", "cuisine_type": "Coffee/Cafe"},
    "Papa D'Amour": {"neighborhood": "Greenwich Village", "cuisine_type": "French"},
    "Papa San": {"neighborhood": "Hudson Yards", "cuisine_type": "Peruvian"},
    "Para Ici": {"neighborhood": "Fort Greene", "cuisine_type": "French"},
    "Parcelle Wine": {"neighborhood": "West Village", "cuisine_type": "Wine Bar"},
    "Pardon my French": {"neighborhood": "East Village", "cuisine_type": "French"},
    "Parla": {"neighborhood": "Upper West Side", "cuisine_type": "Italian"},
    "Pasquale Jones": {"neighborhood": "SoHo", "cuisine_type": "Italian"},
    "Pearl Box": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Peasant": {"neighborhood": "Nolita", "cuisine_type": "Italian"},
    "Penny": {"neighborhood": "East Village", "cuisine_type": "American"},
    "People's": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Petit Chou": {"neighborhood": "Williamsburg", "cuisine_type": "Bakery"},
    "Petit Patate": {"neighborhood": "Greenwich Village", "cuisine_type": "French"},
    "Pheasant": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "The pickle guys": {"neighborhood": "Lower East Side", "cuisine_type": "Deli"},
    "Pinto Garden": {"neighborhood": "West Village", "cuisine_type": "Mediterranean"},
    "Place des Fêtes": {"neighborhood": "Brooklyn", "cuisine_type": "Wine Bar"},
    "Planta Nomad": {"neighborhood": "NoMad", "cuisine_type": "American"},
    "Pomp & Circumstance": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Port Said": {"neighborhood": "Lower East Side", "cuisine_type": "Middle Eastern"},
    "Portale": {"neighborhood": "Chelsea", "cuisine_type": "American"},
    "The Portrait Bar": {"neighborhood": "Midtown", "cuisine_type": "Bar/Cocktails"},
    "Potluck Club": {"neighborhood": "Chelsea", "cuisine_type": "American"},
    "Principe": {"neighborhood": "SoHo", "cuisine_type": "Italian"},
    "Public Records": {"neighborhood": "Gowanus", "cuisine_type": "Bar/Cocktails"},
    "Puglia": {"neighborhood": "Little Italy", "cuisine_type": "Italian"},
    "Pull Tab Coffee": {"neighborhood": "Bryant Park", "cuisine_type": "Coffee/Cafe"},
    
    # === Q ===
    "Question": {"neighborhood": "Lower East Side", "cuisine_type": "American"},
    "Quick Eternity": {"neighborhood": "South Street Seaport", "cuisine_type": "Wine Bar"},
    "Quique Crudo": {"neighborhood": "West Village", "cuisine_type": "Mexican"},
    
    # === R ===
    "RAF's": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Raoul's": {"neighborhood": "SoHo", "cuisine_type": "French"},
    "The Ready Rooftop": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "Reception Bar": {"neighborhood": "Midtown", "cuisine_type": "Bar/Cocktails"},
    "Red Room": {"neighborhood": "FiDi", "cuisine_type": "Bar/Cocktails"},
    "Republic of Booza": {"neighborhood": "Brooklyn", "cuisine_type": "Dessert"},
    "Resident": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "Revelie Luncheonette": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Ribbalta": {"neighborhood": "Union Square", "cuisine_type": "Pizza"},
    "Rigor Hill Market": {"neighborhood": "Ridgewood", "cuisine_type": "American"},
    "Rivareno": {"neighborhood": "SoHo", "cuisine_type": "Dessert"},
    "Ro Burgies": {"neighborhood": "East Village", "cuisine_type": "American"},
    "Rocco's": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Roey's": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Root & Bone": {"neighborhood": "East Village", "cuisine_type": "Southern"},
    "Rose room lounge": {"neighborhood": "Midtown", "cuisine_type": "Bar/Cocktails"},
    "Rosemary's": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Roscioli": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Rubirosa": {"neighborhood": "Nolita", "cuisine_type": "Italian"},
    "Rule of Thirds": {"neighborhood": "Greenpoint", "cuisine_type": "Japanese"},
    
    # === S ===
    "Saint": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Saint Theo's": {"neighborhood": "Prospect Heights", "cuisine_type": "American"},
    "Sakagura": {"neighborhood": "Midtown", "cuisine_type": "Japanese"},
    "Salswee": {"neighborhood": "Upper East Side", "cuisine_type": "Bakery"},
    "Sami and Susu": {"neighborhood": "Brooklyn", "cuisine_type": "Middle Eastern"},
    "San Sabino": {"neighborhood": "Brooklyn", "cuisine_type": "Italian"},
    "Santi": {"neighborhood": "Midtown", "cuisine_type": "Italian"},
    "Scen": {"neighborhood": "West Village", "cuisine_type": "Asian"},
    "Schmuck": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "SEA": {"neighborhood": "NoMad", "cuisine_type": "Japanese"},
    "Setsugekka": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Settepani Bakery": {"neighborhood": "Harlem", "cuisine_type": "Bakery"},
    "Seven Grams Caffe": {"neighborhood": "Multiple", "cuisine_type": "Coffee/Cafe"},
    "Shaken Not Stirred": {"neighborhood": "Upper East Side", "cuisine_type": "Bar/Cocktails"},
    "Shingane": {"neighborhood": "NoMad", "cuisine_type": "Japanese"},
    "Shinji's": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Shirokuro": {"neighborhood": "East Village", "cuisine_type": "Japanese"},
    "Silver Apricot": {"neighborhood": "Greenwich Village", "cuisine_type": "Chinese"},
    "Sip and Guzzle": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Sisters Brooklyn": {"neighborhood": "Clinton Hill", "cuisine_type": "American"},
    "Sloane's": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "Smashed Burger": {"neighborhood": "East Village", "cuisine_type": "American"},
    "Smyth Tavern": {"neighborhood": "Tribeca", "cuisine_type": "American"},
    "The Snail": {"neighborhood": "Brooklyn", "cuisine_type": "American"},
    "Sofreh": {"neighborhood": "Prospect Heights", "cuisine_type": "Persian"},
    "Sogno Toscano": {"neighborhood": "SoHo", "cuisine_type": "Italian"},
    "Sola Pasta Bar": {"neighborhood": "Lower East Side", "cuisine_type": "Italian"},
    "Song E Napule": {"neighborhood": "SoHo", "cuisine_type": "Italian"},
    "Sonnyboy": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Soso's": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Souen": {"neighborhood": "East Village", "cuisine_type": "Japanese"},
    "South SoHo Bar": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "Southern Charm": {"neighborhood": "West Village", "cuisine_type": "Southern"},
    "The Spaniard": {"neighborhood": "West Village", "cuisine_type": "Bar/Cocktails"},
    "Spygold": {"neighborhood": "Hudson Yards", "cuisine_type": "Bar/Cocktails"},
    "St. Jardim": {"neighborhood": "Greenwich Village", "cuisine_type": "American"},
    "Steve's Authentic Key Lime Pies": {"neighborhood": "Red Hook", "cuisine_type": "Dessert"},
    "Stretch Pizza": {"neighborhood": "West Village", "cuisine_type": "Pizza"},
    "Studio 151": {"neighborhood": "Midtown", "cuisine_type": "American"},
    "Suki Desu": {"neighborhood": "Upper East Side", "cuisine_type": "Japanese"},
    "Sunday in Brooklyn": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Sunday to Sunday": {"neighborhood": "Brooklyn", "cuisine_type": "American"},
    "Sunflower Cafe": {"neighborhood": "Williamsburg", "cuisine_type": "American"},
    "Sunlife Organics": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "Sunn's": {"neighborhood": "Lower East Side", "cuisine_type": "Korean"},
    "Super Nice Pizza": {"neighborhood": "Upper West Side", "cuisine_type": "Pizza"},
    "Surreal Creamery": {"neighborhood": "Koreatown", "cuisine_type": "Dessert"},
    "Sushi by Scratch": {"neighborhood": "NoMad", "cuisine_type": "Japanese"},
    "Sushi on Jone": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Sushidelic": {"neighborhood": "Lower East Side", "cuisine_type": "Japanese"},
    "Sushiro": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    
    # === T ===
    "Tacovision": {"neighborhood": "Lower East Side", "cuisine_type": "Mexican"},
    "Tacocina": {"neighborhood": "Williamsburg", "cuisine_type": "Mexican"},
    "Tacos Guey": {"neighborhood": "Williamsburg", "cuisine_type": "Mexican"},
    "Taiko": {"neighborhood": "Chelsea", "cuisine_type": "Greek"},
    "Tall Poppy": {"neighborhood": "Flatiron", "cuisine_type": "Bakery"},
    "Temperance": {"neighborhood": "East Village", "cuisine_type": "Wine Bar"},
    "Temakase": {"neighborhood": "NoMad", "cuisine_type": "Japanese"},
    "Ten Thousand Coffee": {"neighborhood": "Williamsburg", "cuisine_type": "Coffee/Cafe"},
    "Terra": {"neighborhood": "Chelsea", "cuisine_type": "American"},
    "Terrace at Edition": {"neighborhood": "Times Square", "cuisine_type": "American"},
    "Thai Diner": {"neighborhood": "Nolita", "cuisine_type": "Thai"},
    "The Campbell": {"neighborhood": "Midtown", "cuisine_type": "Bar/Cocktails"},
    "The Chocolate Room": {"neighborhood": "Brooklyn", "cuisine_type": "Dessert"},
    "The commerce inn": {"neighborhood": "West Village", "cuisine_type": "American"},
    "The Corner Store": {"neighborhood": "SoHo", "cuisine_type": "Bar/Cocktails"},
    "The Dutch": {"neighborhood": "SoHo", "cuisine_type": "American"},
    "The Four Horsemen": {"neighborhood": "Williamsburg", "cuisine_type": "Wine Bar"},
    "The Fulton": {"neighborhood": "South Street Seaport", "cuisine_type": "Seafood"},
    "The Gallery": {"neighborhood": "Flatiron", "cuisine_type": "Bar/Cocktails"},
    "The Garden at the Standard EV": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "The Highlight Room": {"neighborhood": "Meatpacking", "cuisine_type": "Bar/Cocktails"},
    "The Lavaux": {"neighborhood": "West Village", "cuisine_type": "Wine Bar"},
    "The Little Shop": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "The Love Bakery by Erica": {"neighborhood": "Brooklyn", "cuisine_type": "Bakery"},
    "The Market Line": {"neighborhood": "Lower East Side", "cuisine_type": "Food Hall"},
    "The Smile": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "The Wesley": {"neighborhood": "Upper East Side", "cuisine_type": "American"},
    "The Wooley": {"neighborhood": "FiDi", "cuisine_type": "Bar/Cocktails"},
    "Theodora": {"neighborhood": "Brooklyn", "cuisine_type": "Mediterranean"},
    "This bowl": {"neighborhood": "Multiple", "cuisine_type": "Asian"},
    "Tigre": {"neighborhood": "Lower East Side", "cuisine_type": "Bar/Cocktails"},
    "Time and Tide": {"neighborhood": "Flatiron", "cuisine_type": "Seafood"},
    "Tivoli Trattoria": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Tolo": {"neighborhood": "West Village", "cuisine_type": "Chinese"},
    "Tonchin": {"neighborhood": "Midtown", "cuisine_type": "Japanese"},
    "Tucci": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Twentyonegrains": {"neighborhood": "Hell's Kitchen", "cuisine_type": "American"},
    "Twin Tails": {"neighborhood": "Columbus Circle", "cuisine_type": "Asian"},
    "Two Hands": {"neighborhood": "Nolita", "cuisine_type": "Australian"},
    
    # === U ===
    "Ume": {"neighborhood": "West Village", "cuisine_type": "Japanese"},
    "Una Pizza Napoletana": {"neighborhood": "Lower East Side", "cuisine_type": "Pizza"},
    "Urban Backyard": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Uva": {"neighborhood": "Upper East Side", "cuisine_type": "Italian"},
    
    # === V ===
    "Vallata": {"neighborhood": "West Village", "cuisine_type": "Italian"},
    "Via Porta": {"neighborhood": "East Village", "cuisine_type": "Italian"},
    "Vic's": {"neighborhood": "NoHo", "cuisine_type": "American"},
    "Virginias '": {"neighborhood": "East Village", "cuisine_type": "American"},
    
    # === W ===
    "Waiting on a Friend": {"neighborhood": "East Village", "cuisine_type": "Bar/Cocktails"},
    "Walker Rooftop": {"neighborhood": "Tribeca", "cuisine_type": "Bar/Cocktails"},
    "Westville": {"neighborhood": "West Village", "cuisine_type": "American"},
    "Whipped": {"neighborhood": "West Village", "cuisine_type": "Dessert"},
    "Wildflower": {"neighborhood": "Chelsea", "cuisine_type": "Bar/Cocktails"},
    "Wolfnight's": {"neighborhood": "Brooklyn", "cuisine_type": "American"},
    
    # === X ===
    "Xilonen": {"neighborhood": "NoMad", "cuisine_type": "Mexican"},
    
    # === Y ===
    "Yellow Rose": {"neighborhood": "East Village", "cuisine_type": "Mexican"},
    
    # === Z ===
    "Zehr": {"neighborhood": "West Village", "cuisine_type": "Middle Eastern"},
    "Zimmi's": {"neighborhood": "West Village", "cuisine_type": "French"},
    "ZIZI": {"neighborhood": "Flatiron", "cuisine_type": "Italian"},
    "Zou Zou's": {"neighborhood": "Hudson Yards", "cuisine_type": "Middle Eastern"},
}

def enrich_restaurant(restaurant: dict) -> dict:
    """Enrich a single restaurant with missing data."""
    name = restaurant["name"]
    
    # Check if we have known data for this restaurant
    if name in KNOWN_RESTAURANTS:
        known = KNOWN_RESTAURANTS[name]
        if not restaurant.get("neighborhood"):
            restaurant["neighborhood"] = known.get("neighborhood")
        if not restaurant.get("cuisine_type"):
            restaurant["cuisine_type"] = known.get("cuisine_type")
    
    return restaurant

def main():
    # Load existing data
    with open("data/restaurants.json") as f:
        restaurants = json.load(f)
    
    # Count before
    before_neighborhood = sum(1 for r in restaurants if r.get("neighborhood"))
    before_cuisine = sum(1 for r in restaurants if r.get("cuisine_type"))
    
    # Enrich each restaurant
    for restaurant in restaurants:
        enrich_restaurant(restaurant)
    
    # Count after
    after_neighborhood = sum(1 for r in restaurants if r.get("neighborhood"))
    after_cuisine = sum(1 for r in restaurants if r.get("cuisine_type"))
    
    # Save enriched data
    with open("data/restaurants.json", "w") as f:
        json.dump(restaurants, f, indent=2)
    
    print(f"Enriched {len(restaurants)} restaurants")
    print(f"Neighborhoods: {before_neighborhood} -> {after_neighborhood}")
    print(f"Cuisine types: {before_cuisine} -> {after_cuisine}")
    
    # Show restaurants still missing data
    missing_neighborhood = [r["name"] for r in restaurants if not r.get("neighborhood")]
    missing_cuisine = [r["name"] for r in restaurants if not r.get("cuisine_type")]
    
    print(f"\nStill missing neighborhood: {len(missing_neighborhood)}")
    if missing_neighborhood:
        print("Missing:", missing_neighborhood[:20])
    
    print(f"\nStill missing cuisine: {len(missing_cuisine)}")
    if missing_cuisine:
        print("Missing:", missing_cuisine[:20])

if __name__ == "__main__":
    main()
